### ISSUE TITLE
Problem with HouseNumberSuffix Embedded in Address Field

### ISSUE THREAD

**Issue by rstanton00** [adthom/TeamsE911Automation#3]
I work for a large public university with tens of thousands of locations at 385 unique street addresses.  We are having difficulty importing some of our address data with your CSV file format, StringlyTypedDataStructure.txt.

The address field in the code currently consists of six fields: HouseNumber, HouseNumberSuffix, PreDirectional, StreetName, StreetSuffix, and PostDirectional.  We have a number of house number suffixes that are not making it into Teams LIS when using this format.  It would greatly benefit us to have a version of this code that uses six comma separated values for these six fields instead of a single Address field (23 total fields in StringlyTypedDataStructure.txt instead of the current 18).  We have these fields broken out and are currently concatenating them together to build the Address field for the TeamsE911Automation code, which then parses the address and does not end up with the same result we put in.

An example of this would be '1205 1/2 W Nevada St', and the house number suffix does not make it into Teams LIS.  For our purposes, it is important that the '1/2' be included, as it represents an entirely separate freestanding structure that first responders need to be able to distinguish clearly from 1205.

**Comment by adthom** [comment]
I think that I have a working version that will properly parse out house number suffixes ready now. I will be pushing it shortly.
